### PR TITLE
Escape HTML in code blocks

### LINKED ISSUE #9: BUG: renders html
md"""

<triple-back-quotes>html

<triple-back-ticks/quotes>
"""

is rendered in html page. I should not. Should wrapper around <code></code>

Screenshot 2021-11-05 at 2 09 38 PM

### PR DESCRIPTION
**Pull request by rikhuijzer**
Close #9

### CODE REVIEW

**Comment by rikhuijzer** [comment]
@AbhimanyuAryan only inside code is escaped now:

```
julia> using PlutoStaticHTML

julia> using Pluto: Cell, Notebook

julia> cell = Cell("\"<b>foo</b>\"");

julia> nb = Notebook([cell]);

julia> notebook2html(nb) |> print
<pre><code class="language-julia">"&lt;b&gt;foo&lt;/b&gt;"</code></pre>
<pre><code class="code-output">"<b>foo</b>"</code></pre>
```

Output HTML styling is important for things like Markdown blocks `md"this is **bold**"`.

**Comment by AbhimanyuAryan** [comment]
Maybe implement a separate rule for this

```
Pluto Cell 
# HTML-block

our HTML code 

End Pluto Cell
```

**Comment by AbhimanyuAryan** [comment]
Where we can check for comment apply this to selective cells

**Comment by AbhimanyuAryan** [comment]
Ok I'll check tomorrow morning 👌🏼

**Pull request merged**
